python/blog/blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/",include("bolg.urls",namespace="blog"))
]

python/blog/bolg/urls.py
from django.urls import path
from bolg import views

app_name="blog"
urlpatterns = [
    path("",views.post_list,name="post_list"),
    path('tag/<slug:tag_slug>',views.post_list,name='post_list_by_tag'),
    # path('',views.PostListView.as_view(),name='post_list'),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>/",
         views.post_detail,name ="post_detail"),
    path("<int:post_id>/share/",views.post_share,name="post_share")
]

python/blog/bolg/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# 数据架构 data schema
# schema 是一个数据库名词，一般指的是数据在数据库的组织模式或者说是架构
# Create your models here.
# queryset 查询结果集对象


# post.objects.my_manager（） 提供一个新方法
# post.my_manager.all()

# 创建模型管理器
class PublishManager(models.Manager):
    def get_queryset(self):
        return super(PublishManager,self).get_queryset().filter(status="publish")


class Post(models.Model):
    STATUS_CHOICES = (("draft","草稿"),("publish","发布"))
    title = models.CharField(max_length=300,verbose_name="标题")
    slug = models.SlugField(max_length=200,unique_for_date="publish")
    # related_name 设置从user到post的反向关联关系，用bolg_post为这个
    # 反向关联关系命名
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="blog_posts")
    body = models.TextField()
    # timezone.now 包含时区的时间对象
    publish = models.DateTimeField(default=timezone.now)
    # auto_now_add 表示当创建一行数据的时候，自动用创建数据的时间填充
    created = models.DateTimeField(auto_now_add=True)
    # auto_now 表示每次更新数据的时候，都会用当前的时间填充
    updatad = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default="draft")

    class Meta:
        db_table = "blog" # 表名
        ordering = ("-publish",)

    def __str__(self):
        return self.title

    objects = models.Manager() # 默认的管理器
    publishde = PublishManager() #自定义的管理器
    tags = TaggableManager()#taggit的模型管理器

    # 创建超链接到具体的数据对象
    def get_absolute_url(self):
        return reverse("blog:post_detail",args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])


class Comment(models.Model):
    # 评论 post.comment_set
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'comment'
        ordering = ('created',)

    def __str__(self):
        return "comment title {} on {}".format(self.name,self.post)

python/blog/bolg/forms.py
from django import forms
from .models import Comment
# django使用两个类来创建表单
# forms.Form 用于生成标准的表单
# forms.ModelForm 用于从模型中生成表单

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=35)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name","email","body")
        # exclude 属性指定需要排除的字段
        # exclude = ("created")

python/blog/bolg/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Create your views here.

# FBV 函数视图
# CBV 类视图
# mixins 可服用的类模块

class PostListView(ListView):
    # model = Post
    # queryset 查询所有已发布的文章
    # 可以不用queryset，通过指定model=Post，会进行post.objects.all()查询获得所有的文章
    queryset = Post.publishde.all()
    # 设置posts为模板变量的名称，不过不设置， 默认的名称就是object_list
    context_object_name = "posts"
    paginate_by = 2
    template_name = "blog/post/list.html"
    #返回分页的变量的名称是page_obj



def post_list(request,tag_slug = None):
    posts = Post.publishde.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    paginator = Paginator(posts,2) #每页显示两篇文章
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果page参数不是一个整数，就返回第一页
        posts = paginator.page(1)
    except EmptyPage:
        # 如果页数超出总页数那就返回最后一页
        posts = paginator.page(paginator.num_pages)

    return render(request,"blog/post/list.html",{"posts":posts,"page":page,
                                                 "tag":tag})

def post_detail(request,year,month,day,slug):
    post = get_object_or_404(Post,slug=slug,status="publish",publish__year=year,
                             publish__month = month,publish__day = day)

    # 列出文章的所有活动的评论
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method =="POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # 通过表单直接创建新的数据对象，但是不保存在数据库中
            new_comment = comment_form.save(commit=False)
            # 设置外键为当前文章
            new_comment.post = post
            # 最后将评论写入数据库
            new_comment.save()
    else:
        comment_form = CommentForm()
    # 显示相近的tag列表
    # flat = True 让结果变成一个列表[1,2..]
    post_tags_id = post.tags.values_list("id",flat=True)
    similar_tags = Post.publishde.filter(tags__in=post_tags_id).exclude(id=post.id)
    # 使用count 对每个文章按照标签计数， 并且生成一个新的字段same_tags用于存放计数的结果
    similar_posts = similar_tags.annotate(same_tags=Count("tags")).order_by("-same_tags","-publish")[:2]
    return render(request,"blog/post/detail.html",{"post":post,
                                                   "comments":comments,
                                                   "new_comment":new_comment,
                                                   "comment_form":comment_form,
                                                   "similar_posts":similar_posts})

def post_share(request,post_id):
    # 通过id获取post对象
    post = get_object_or_404(Post,id=post_id,status = "publish")
    send = False
    if request.method == "POST":
    #     表单被提交
        form = EmailPostForm(request.POST)
        # 如果返回false，form.errors
        if form.is_valid():
            #验证表单通过
            cd = form.cleaned_data
            #发送邮件
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = "{} share reding".format(cd["name"])
            message = "read comments {},文章的连接是:{}".format(cd["comments"],
                                                        post_url)
            send_mail(subject,message,cd["email"],[cd["to"]])
    else:
        # 创建一个空白的form对象，展示在页面中是一个空白的表单供用户去填写
        form = EmailPostForm()
    return render(request,"blog/post/share.html",{"post":post,
                                                  "form":form,"send":send})

python/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        发布日期：{{ post.publish }}
        作者: {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}"> 分享这篇文章</a>
    </p>
    <h3>你可能喜欢的文章</h3>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>没有相似的文章</p>
    {% endfor %}

    <h2>总共{{ comments.count }}条评论</h2>
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                第{{ forloop.counter }}条评论 评论人：{{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>这篇文章还没有任何评论</p>
    {% endfor %}

    {% if new_comment %}
        <h2>你的评论已被添加</h2>
    {% else %}
        <h2>添加一个新的评论</h2>
        <form action="." method="POST">
            {% csrf_token %}
            {{ comment_form.as_table }}
            <input type="submit" value="添加评论">
        </form>
    {% endif %}
{% endblock %}

python/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}

</ul>

python/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}
    我的blog
{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
            <p class="tags">
                标签:
                {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                    {% if not forloop.last %}
                        ,
                    {% endif %}
                {% endfor %}
            </p>
        </h2>
        <p class="date">
            发布日期：{{ post.publish }}
            作者：{{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
        {{ 1|posts_add:3 }}
    {% endfor %}
    {% include "paginator.html" with page=posts %}
{% endblock %}

python/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    分享一篇文章
{% endblock %}

{% block content %}
    {% if send %}
        <h1>Email 已经发送成功</h1>
    {% else %}
        <h1>分享{{ post.title }}</h1>
        <form action="." method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="发送邮件">
        </form>
    {% endif %}
{% endblock %}