python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/myPro/urls.py
from django.contrib import admin
from django.urls import path,include
from subject.views import index
from user.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),

    path('',LoginView.as_view(),name='index'),
    path('subject/',include('subject.urls',namespace='subject')),
    path('stage/',include('stage.urls')),
    path('outline/',include('outline.urls',namespace='outline')),
    path('program/',include('program.urls',namespace='program'))
]

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/outline/urls.py
from django.urls import path,re_path

from .views import OutlineView,DetailView,AddView,EditView,DeleteView

app_name='outline'
urlpatterns = [
    path('list/',OutlineView.as_view(),name='outline_list'),
    path('detail/',DetailView.as_view(),name='detail'),
    path('add/',AddView.as_view(),name='add'),
    path('edit/',EditView.as_view(),name='edit'),
    path('delete/',DeleteView.as_view(),name='delete')
]

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/user/urls.py
from django.urls import path

from . views import RegisterView,LoginView,LogOutView ,test_json

urlpatterns = [
    path(r'register/',RegisterView.as_view(),name='register'),
    path(r'login/',LoginView.as_view(),name='login'),
    # 注销
    path('logout/',LogOutView.as_view(),name='logout'),
    path('json_test/',test_json)
]

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/outline/models.py
from django.db import models
from django.contrib import admin
from stage.models import StageModel
import datetime
# Create your models here.

class OutlineModel(models.Model):
    stages = StageModel.objects.all()
    stage_id_name = [(stage.id, stage.title) for stage in stages]

    stage_id = models.IntegerField(default=0, verbose_name='阶段id',choices=stage_id_name)
    number = models.IntegerField(default=0,verbose_name='序号',null=False)
    title = models.CharField(max_length=255,null=False,verbose_name='标题')
    days = models.IntegerField(default=0,null=False,verbose_name='学时')
    advancing = models.CharField(max_length=255,null=False,verbose_name='高级内容')
    remark = models.CharField(max_length=255,null=True,verbose_name='备注')
    status = models.IntegerField(default=0)
    creater = models.IntegerField(default=0,verbose_name='创建者')
    create_time = models.DateTimeField(default=datetime.datetime.now(),verbose_name='创建时间')
    updater = models.IntegerField(default=0,verbose_name='更新者')
    update_time = models.DateTimeField(default=datetime.datetime.now(),verbose_name='更新时间')

@admin.register(OutlineModel)
class OutlineAdminModel(admin.ModelAdmin):
    list_display = ('title','advancing')

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/outline/views.py
from django.shortcuts import render,redirect,render_to_response
from django.views import View
from .models import OutlineModel
from stage.models import StageModel
# Create your views here.

class OutlineView(View):
    def get(self,request):
        stage_id = request.GET['stage_id']
        outline = OutlineModel.objects.filter(stage_id=stage_id)
        return render_to_response('outline/outline_list.html',{'outlines':outline})

class DetailView(View):
    def get(self,request):
        outline_id = request.GET['outline_id']
        outline = OutlineModel.objects.get(id=outline_id)
        stage = StageModel.objects.get(id=outline.stage_id)
        return render_to_response('outline/detail.html',{'outline':outline,'stage':stage})

class EditView(View):
    def get(self,request):
        outline_id = request.GET['outline_id']
        outline = OutlineModel.objects.get(id=outline_id)
        return render_to_response('outline/edit.html',{'outlines':outline})
    def post(self,request):
        outline_id = request.POST['outline_id']
        title = request.POST['title']
        number = request.POST['number']
        days = request.POST['days']
        advancing = request.POST['advancing']
        remark = request.POST['remark']
        outline = OutlineModel.objects.get(id=outline_id)
        if outline:
            outline.title = title
            outline.number = number
            outline.days = days
            outline.advancing = advancing
            outline.remark = remark
            outline.save()
        return redirect('/outline/detail/?outline_id={outline_id}&stage_id={stage_id}'.format(outline_id=outline_id,stage_id=outline.stage_id))

class DeleteView(View):
    def get(self,request):
        outline_id = request.GET['outline_id']
        outline = OutlineModel.objects.get(id=outline_id)
        stage_id = outline.stage_id
        if outline:
            outline.delete()
        return redirect('/outline/list/?stage_id=' + str(stage_id))

class AddView(View):
    def get(self,request):
        stage = StageModel.objects.all()
        return render_to_response('outline/add.html',{'stages':stage})
    def post(self,request):

        stage_id = request.POST['stage_id']
        title = request.POST['title']
        number = request.POST['number']
        days = request.POST['days']
        advancing = request.POST['advancing']
        remark = request.POST['remark']

        outline = OutlineModel()
        outline.stage_id = stage_id
        outline.title = title
        outline.number = number
        outline.days = days
        outline.advancing = advancing
        outline.remark =remark
        outline.save()

        return redirect('/outline/list/?stage_id=' +str(stage_id))

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/outline/add.html
{% extends 'base.html'%}

{% block title%}
一级大纲增加
{% endblock %}

{% block style%}
<style>
    .container{
        position: relative;
    }
    .navbar{
        margin-bottom: 0;
    }
    #loginName{
        position: absolute;
        right: 0;
    }
    h2{
        margin: 0;
        padding: 12px 0;
        font-size: 20px;
        background-color: lightgray;
    }
    form{
        padding-left: 180px;
    }
</style>
{% endblock%}

{% block main%}
<h2>
    <div class="container">
        <div>添加一级大纲</div>
    </div>
</h2>
<form class="form-horizontal" role="form" action="{% url 'outline:add'%}" method="POST">
    {% csrf_token %}
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">阶段id</label>
        <div class="col-sm-3">
            <select class="form-control" name="stage_id">
                {% for stage in stages %}
                <option value="{{ stage.id }}">{{stage.title}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="title" class="col-sm-2 control-label">一级大纲标题</label>
        <div class="col-sm-3">
            <input name="title" type="text" class="form-control" id="title" placeholder="请输入标题">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="number" class="col-sm-2 control-label">排序</label>
        <div class="col-sm-2">
            <input name="number" type="number" class="form-control" id="number" placeholder="0">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="days" class="col-sm-2 control-label">学时</label>
        <div class="col-sm-2">
            <input name="days" type="text" class="form-control" id="days" placeholder="0">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="advancing" class="col-sm-2 control-label">高级内容</label>
        <div class="col-sm-6">
            <input name="advancing" type="text" class="form-control" id="advancing" placeholder="">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">备注</label>
        <div class="col-sm-10">
            <textarea name="remark" id="remark" cols="70" rows="10" placeholder="请填写备注"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
            <button type="submit" class="btn btn-success btn-block">提交</button>
        </div>
    </div>
    <br>
</form>
{% endblock %}

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/outline/detail.html
{% extends 'base.html'%}

{% block title%}
一级大纲详情
{% endblock%}

{% block style%}
<style>
     h2{
            margin: 0;
            padding: 12px 0;
            font-size: 20px;
            background-color: lightgray;
        }
    .navbar{
        margin-bottom: 0;
    }
    span{
        font-weight: 600;
        font-size: 20px;
    }
</style>
{% endblock %}
{% block main %}
<h2>
    <div class="container">
       一级大纲详情
    </div>
</h2>

<div class="container">
    <br><br>

    <div>
        <span>序号</span>
        <br><br>
        {{outline.number}}
    </div>
    <br>
    <div>
        <span>标题</span>
         <br><br>
        {{outline.title}}
    </div>
    <br>
    <div>
        <span>学时</span>
         <br><br>
        {{outline.days}}天
    </div>
    <br>
    <div>
        <span>学习方法</span>
         <br><br>
        {{outline.advancing}}
    </div>
    <br>
    <div>
        <span>备注</span>
        <br><br>
        {{outline.remark}}
    </div>
</div>
{% endblock %}

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/outline/edit.html
{% extends 'base.html'%}

{% block title%}
一级大纲修改
{% endblock %}

{% block style%}
<style>
    .container{
        position: relative;
    }
    .navbar{
        margin-bottom: 0;
    }
    #loginName{
        position: absolute;
        right: 0;
    }
    h2{
        margin: 0;
        padding: 12px 0;
        font-size: 20px;
        background-color: lightgray;
    }
    form{
        padding-left: 180px;
    }
</style>
{% endblock%}

{% block main%}
<h2>
    <div class="container">
        <div>修改一级大纲</div>
    </div>
</h2>
<form class="form-horizontal" role="form" action="{% url 'outline:edit'%}" method="POST">
    {% csrf_token %}
    <br>
    <input type="hidden" name="outline_id" id="outline_id" value="{{outlines.id}}">
    <div class="form-group">
        <label for="title" class="col-sm-2 control-label">一级大纲标题</label>
        <div class="col-sm-3">
            <input name="title" type="text" class="form-control" id="title" value="{{outlines.title}}">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="number" class="col-sm-2 control-label">排序</label>
        <div class="col-sm-2">
            <input name="number" type="number" class="form-control" id="number" value="{{outlines.number}}">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="days" class="col-sm-2 control-label">学时</label>
        <div class="col-sm-2">
            <input name="days" type="text" class="form-control" id="days" value="{{outlines.days}}">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="advancing" class="col-sm-2 control-label">高级内容</label>
        <div class="col-sm-6">
            <input name="advancing" type="text" class="form-control" id="advancing" value="{{outlines.advancing}}">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="remark" class="col-sm-2 control-label">备注</label>
        <div class="col-sm-10">
            <textarea name="remark" id="remark" cols="70" rows="10" placeholder="请填写备注"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
            <button type="submit" class="btn btn-success btn-block">提交</button>
        </div>
    </div>
    <br>
</form>
{% endblock %}

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/outline/outline_list.html
{% extends 'base.html'%}

{% block title%}
教学大纲管理系统
{% endblock %}

{% block style%}
<style>
    a{
        color: gray;
    }
</style>
{% endblock%}

{% block main%}
<div class="container">
    <h2 class="text-center">一级大纲</h2>
    {% for outline in outlines %}
    <div class="text-center">
        <br>
        <a style="font-size: 15px;font-weight: 600;color:black" href="/program/list/?outline_id={{outline.id}}">{{outline.title}} ({{outline.days}}天)</a>&#x3000;
        <a href="/outline/detail/?outline_id={{outline.id}}&stage_id={{stage.id}}"><span class="glyphicon glyphicon-list"></span></a>
        <a href="/outline/edit/?outline_id={{outline.id}}"><span class="glyphicon glyphicon-edit"></span></a>
        <a href="/outline/delete/?outline_id={{outline.id}}"><span class="glyphicon glyphicon-remove-circle"></span></a>
        <br><br>
        <div style="color: gray">{{outline.advancing}}</div>
    </div>

    <br>
    <div class="text-center">
        <span class="glyphicon glyphicon-arrow-down"></span>
    </div>
    <br>
    {% endfor %}
    <div class="text-center">
        <a style="font-size: 20px" href="/outline/add/">
            <span class="glyphicon glyphicon-plus-sign"></span>
        </a>
    </div>
</div>
{% endblock %}