python/第十五周：课件/fresh/fresh/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 加入user的路由
    path('account/', include("user.urls", namespace="user")),
    # 加入商品的路由
    path('goods/', include("goods.urls", namespace="goods"))
]

python/第十五周：课件/fresh/user/urls.py
from django.urls import path

from user.views import register, register_post, login, info, logout
# 命名空间名字
app_name = "user"
urlpatterns = [
    path("register/", register, name="register"),
    path("register_post/", register_post, name="register_post"),
    # 登陆接口
    path("login/", login, name="login"),
    # 用户信息接口
    path("info/", info, name="info"),
    # 退出登陆
    path("logout/", logout, name="logout")
]

python/第十五周：课件/fresh/templates/base_footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

	<link href="/static/css/reset.css" rel="stylesheet" type="text/css">
	<link href="/static/css/main.css" rel="stylesheet" type="text/css">
	<script src="/static/js/jquery-1.12.4.min.js" type="text/javascript"></script>
{#	<script src="/static/js/register.js" type="text/javascript"></script>#}
{#	<script src="/static/js/login.js" type="text/javascript"></script>#}
    {% block head %}
    {% endblock %}
    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>
<body>
{% block main %}
{% endblock %}
<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
</body>
</html>

python/第十五周：课件/fresh/templates/base_header.html
{% extends "base_footer.html" %}

{% block main %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if request.session.username %}
                    <div class="login_btn fl">
					    欢迎您：<em>{{ request.session.username }}</em>
                        <span>|</span>
                        <a href="/account/logout/">注销</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
					    <a href="{% url 'user:login' %}">登录</a>
					    <span>|</span>
					    <a href="{% url 'user:register' %}">注册</a>
				    </div>
                {% endif %}

				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:info' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>
    {% block cart %}
    <div class="search_bar clearfix">
		<a class="logo fl" href="index.html"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
		<div class="search_con fr">
			<input class="input_text fl" type="text" placeholder="搜索商品">
			<input class="input_btn fr" type="button" value="搜索">
		</div>
    </div>
    {% endblock %}

    {% block body %}
    {% endblock %}
{% endblock %}

python/第十五周：课件/fresh/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
aaa
<form enctype="multipart/form-data">
    {{ user_form.as_p }}
</form>

</body>
</html>