python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/myPro/urls.py
from django.contrib import admin
from django.urls import path,include
from subject.views import index
from user.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('user.urls')),

    path('',LoginView.as_view(),name='index'),
    path('subject/',include('subject.urls',namespace='subject')),
    path('stage/',include('stage.urls')),
    path('outline/',include('outline.urls',namespace='outline')),
    path('program/',include('program.urls',namespace='program'))
]

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/program/urls.py
from django.urls import path
from .views import ProgramView,AddView,EditView,DetailView,DeleteView

app_name='program'
urlpatterns = [
    path('list/',ProgramView.as_view(),name='program_list'),
    path('add/',AddView.as_view(),name='add'),
    path('edit/',EditView.as_view(),name='edit'),
    path('detail/',DetailView.as_view(),name='detail'),
    path('delete/',DeleteView.as_view(),name='delete')
]

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/user/urls.py
from django.urls import path

from . views import RegisterView,LoginView,LogOutView ,test_json

urlpatterns = [
    path(r'register/',RegisterView.as_view(),name='register'),
    path(r'login/',LoginView.as_view(),name='login'),
    # 注销
    path('logout/',LogOutView.as_view(),name='logout'),
    path('json_test/',test_json)
]

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/program/models.py
from django.db import models
from django.contrib import admin
import datetime
from outline.models import OutlineModel
from stage.models import StageModel
# Create your models here.
class ProgramModel(models.Model):
    stages = StageModel.objects.all()
    outlines = OutlineModel.objects.all()

    stage_id_name = [(stage.id, stage.title) for stage in stages]
    outline_id_name = [(outline.id,outline.title) for outline in outlines]

    stage_id = models.IntegerField(default=0, verbose_name='阶段id',choices=stage_id_name)
    outline_id = models.IntegerField(default=0,verbose_name='一级大纲id',choices=outline_id_name)
    number = models.IntegerField(default=0,null=False,verbose_name='排序')
    sign = models.CharField(max_length=255,null=False,verbose_name='标志性内容')
    digest = models.CharField(max_length=255,verbose_name='内容摘要',null=False)
    propare = models.CharField(max_length=255,verbose_name='准备工作',null=False)
    process = models.CharField(max_length=255,verbose_name='讲课流程',null=False)
    attention = models.CharField(max_length=255,verbose_name='准备工作',null=False)
    exercise = models.CharField(max_length=255,verbose_name='课后作业',null=False)
    share = models.CharField(max_length=255,verbose_name='学生分享',null=False)
    management = models.CharField(max_length=255,verbose_name='管理事项',null=False)
    remark = models.CharField(max_length=255,verbose_name='备注',null=True)
    status = models.IntegerField(default=0,null=True)
    creater = models.IntegerField(default=0,verbose_name='创建者',null=True)
    create_time = models.DateTimeField(default=datetime.datetime.now(),verbose_name='创建时间')
    updater = models.IntegerField(default=0,verbose_name='更新者')
    update_time = models.DateTimeField(default=datetime.datetime.now(),verbose_name='更新时间')

@admin.register(ProgramModel)
class ProgramAdminModel(admin.ModelAdmin):
    list_display = ('number','sign')

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/program/views.py
from django.shortcuts import render,render_to_response,redirect
from django.views import View
from .models import ProgramModel
from stage.models import StageModel
from outline.models import OutlineModel

# Create your views here.
class ProgramView(View):
    def get(self,request):
        outline_id = request.GET['outline_id']

        program = ProgramModel.objects.filter(outline_id=outline_id)
        outline = OutlineModel.objects.filter(id=outline_id)
        return render_to_response('program/program_list.html',{'programs':program,'outlines':outline})

class DetailView(View):
    def get(self,request):
        program_id = request.GET['program_id']
        program = ProgramModel.objects.get(id=program_id)
        outline = OutlineModel.objects.get(id=program.outline_id)
        return render_to_response('program/detail.html', {'program': program, 'outline': outline})

class AddView(View):
    def get(self,request):
        stage = StageModel.objects.all()
        outline = OutlineModel.objects.all()
        return render_to_response('program/add.html', {'stages': stage,'outlines':outline})
    def post(self,request):
        stage_id = request.POST['stage_id']
        ouline_id = request.POST['outline_id']
        number = request.POST['number']
        sign = request.POST['sign']
        digest = request.POST['digest']
        prepare = request.POST['prepare']
        process = request.POST['process']
        attention = request.POST['attention']
        exercise = request.POST['exercise']
        share = request.POST['share']
        management = request.POST['management']
        remark = request.POST['remark']

        program = ProgramModel()
        program.stage_id = stage_id
        program.outline_id = ouline_id
        program.number = number
        program.sign = sign
        program.digest = digest
        program.propare = prepare
        program.process = process
        program.attention = attention
        program.exercise = exercise
        program.share = share
        program.management = management
        program.remark = remark
        program.save()

        return redirect('/program/list/?outline_id=' + str(ouline_id))

class EditView(View):
    def get(self,request):
        program_id = request.GET['program_id']
        program = ProgramModel.objects.get(id=program_id)
        stage = StageModel.objects.all()
        outline = OutlineModel.objects.all()

        return render_to_response('program/edit.html',{'program':program,'stage':stage,'outline':outline})
    def post(self,request):
        program_id = request.POST['program_id']
        stage_id = request.POST['stage_id']
        outline_id = request.POST['outline_id']
        number = request.POST['number']
        sign = request.POST['sign']
        digest = request.POST['digest']
        prepare = request.POST['prepare']
        process = request.POST['process']
        attention = request.POST['attention']
        exercise = request.POST['exercise']
        share = request.POST['share']
        management = request.POST['management']
        remark = request.POST['remark']

        program = ProgramModel.objects.get(id=program_id)
        if program:
            program.stage_id = stage_id
            program.outline_id = outline_id
            program.number = number
            program.sign = sign
            program.digest = digest
            program.propare = prepare
            program.process = process
            program.attention = attention
            program.exercise = exercise
            program.share = share
            program.management = management
            program.remark = remark
            program.save()

        return redirect('/program/detail/?program_id={program_id}&outline_id={outline_id}'.format(program_id=program_id,outline_id=program.outline_id))

class DeleteView(View):
    def get(self,request):
        program_id = request.GET['program_id']
        program = ProgramModel.objects.get(id=program_id)
        outline_id = program.outline_id
        if program:
            program.delete()
        return redirect('/program/list/?outline_id=' + str(outline_id))

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/program/add.html
{% extends 'base.html'%}

{% block title%}
二级大纲增加
{% endblock %}

{% block style%}
<style>
    .container{
        position: relative;
    }
    .navbar{
        margin-bottom: 0;
    }
    #loginName{
        position: absolute;
        right: 0;
    }
    h2{
        margin: 0;
        padding: 12px 0;
        font-size: 20px;
        background-color: lightgray;
    }
    form{
        padding-left: 180px;
    }
</style>
{% endblock%}

{% block main%}
<h2>
    <div class="container">
        <div>添加二级大纲</div>
    </div>
</h2>
<form class="form-horizontal" role="form" action="{% url 'program:add'%}" method="POST">
    {% csrf_token %}
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">阶段id</label>
        <div class="col-sm-3">
            <select class="form-control" name="stage_id">
                {% for stage in stages %}
                <option value="{{ stage.id }}">{{stage.title}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">一级大纲id</label>
        <div class="col-sm-3">
            <select class="form-control" name="outline_id">
                {% for outline in outlines %}
                <option value="{{ outline.id }}">{{outline.title}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="number" class="col-sm-2 control-label">天序</label>
        <div class="col-sm-2">
            <input name="number" type="number" class="form-control" id="number" placeholder="0">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="sign" class="col-sm-2 control-label">标志性内容</label>
        <div class="col-sm-2">
            <input name="sign" type="text" class="form-control" id="sign" placeholder="">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="digest" class="col-sm-2 control-label">内容摘要</label>
        <div class="col-sm-10">
            <textarea name="digest" id="digest" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br><div class="form-group">
    <label for="prepare" class="col-sm-2 control-label">准备工作</label>
    <div class="col-sm-10">
        <textarea name="prepare" id="prepare" cols="70" rows="5" placeholder=""></textarea>
    </div>
</div>
    <br>
    <div class="form-group">
        <label for="process" class="col-sm-2 control-label">讲课流程</label>
        <div class="col-sm-10">
            <textarea name="process" id="process" cols="70" rows="10" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="attention" class="col-sm-2 control-label">注意事项</label>
        <div class="col-sm-10">
            <textarea name="attention" id="attention" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="exercise" class="col-sm-2 control-label">课后作业</label>
        <div class="col-sm-10">
            <textarea name="exercise" id="exercise" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="share" class="col-sm-2 control-label">学生分享</label>
        <div class="col-sm-10">
            <textarea name="share" id="share" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="management" class="col-sm-2 control-label">管理事项</label>
        <div class="col-sm-10">
            <textarea name="management" id="management" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">备注</label>
        <div class="col-sm-10">
            <textarea name="remark" id="remark" cols="70" rows="5" placeholder="请填写备注"></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
            <button type="submit" class="btn btn-success btn-block">提交</button>
        </div>
    </div>
    <br>
</form>
{% endblock %}

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/program/detail.html
{% extends 'base.html'%}

{% block title%}
二级大纲详情
{% endblock%}

{% block style%}
<style>
     h2{
            margin: 0;
            padding: 12px 0;
            font-size: 20px;
            background-color: lightgray;
        }
    .navbar{
        margin-bottom: 0;
    }
    span{
        font-weight: 600;
        font-size: 20px;
    }
</style>
{% endblock %}
{% block main %}
<h2>
    <div class="container">
       二级大纲详情
    </div>
</h2>

<div class="container">
    <br><br>

    <div>
        <span>天序</span>
        <br><br>
        第{{program.number}}天
    </div>
    <br>
    <div>
        <span>标志性内容</span>
         <br><br>
        {{program.sign}}
    </div>
    <br>
    <div>
        <span>内容摘要</span>
         <br><br>
        {{program.digest}}
    </div>
    <br>
    <div>
        <span>课后作业</span>
         <br><br>
        {{program.exercise}}
    </div>
    <br>
    <div>
        <span>备注</span>
        <br><br>
        {{program.remark}}
    </div>
</div>
{% endblock %}

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/program/edit.html
{% extends 'base.html'%}

{% block title%}
二级大纲修改
{% endblock %}

{% block style%}
<style>
    .container{
        position: relative;
    }
    .navbar{
        margin-bottom: 0;
    }
    #loginName{
        position: absolute;
        right: 0;
    }
    h2{
        margin: 0;
        padding: 12px 0;
        font-size: 20px;
        background-color: lightgray;
    }
    form{
        padding-left: 180px;
    }
</style>
{% endblock%}

{% block main%}
<h2>
    <div class="container">
        <div>修改二级大纲</div>
    </div>
</h2>
<form class="form-horizontal" role="form" action="{% url 'program:edit'%}" method="POST">
    {% csrf_token %}
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">阶段id</label>
        <div class="col-sm-3">
            <select class="form-control" name="stage_id">
                {% for stage in stage %}
                <option value="{{ stage.id }}">{{stage.title}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">一级大纲id</label>
        <div class="col-sm-3">
            <select class="form-control" name="outline_id">
                {% for outline in outline %}
                <option value="{{ outline.id }}">{{outline.title}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="number" class="col-sm-2 control-label">天序</label>
        <div class="col-sm-2">
            <input name="number" type="number" class="form-control" id="number"value="{{programs.number}}">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="sign" class="col-sm-2 control-label">标志性内容</label>
        <div class="col-sm-2">
            <input name="sign" type="text" class="form-control" id="sign" value="{{programs.sign}}">
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="digest" class="col-sm-2 control-label">内容摘要</label>
        <div class="col-sm-10">
            <textarea name="digest" id="digest" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br><div class="form-group">
    <label for="prepare" class="col-sm-2 control-label">准备工作</label>
    <div class="col-sm-10">
        <textarea name="prepare" id="prepare" cols="70" rows="5" placeholder=""></textarea>
    </div>
</div>
    <br>
    <div class="form-group">
        <label for="process" class="col-sm-2 control-label">讲课流程</label>
        <div class="col-sm-10">
            <textarea name="process" id="process" cols="70" rows="10" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="attention" class="col-sm-2 control-label">注意事项</label>
        <div class="col-sm-10">
            <textarea name="attention" id="attention" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="exercise" class="col-sm-2 control-label">课后作业</label>
        <div class="col-sm-10">
            <textarea name="exercise" id="exercise" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="share" class="col-sm-2 control-label">学生分享</label>
        <div class="col-sm-10">
            <textarea name="share" id="share" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="management" class="col-sm-2 control-label">管理事项</label>
        <div class="col-sm-10">
            <textarea name="management" id="management" cols="70" rows="5" placeholder=""></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <label for="" class="col-sm-2 control-label">备注</label>
        <div class="col-sm-10">
            <textarea name="remark" id="remark" cols="70" rows="5" placeholder="请填写备注"></textarea>
        </div>
    </div>
    <br>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-3">
            <input type="hidden" name="program_id" id="program_id" value="{{program.id}}">
            <button type="submit" class="btn btn-success btn-block">提交</button>
        </div>
    </div>
    <br>
</form>
{% endblock %}

python/9/21/1.智游教学管理系统 登陆注册首页学科列表/myPro/templates/program/program_list.html
{% extends 'base.html'%}

{% block title%}
教学大纲管理系统
{% endblock %}

{% block style%}
<style>
    main{
        border: 1px solid lightgray;
    }
    main>div{
        border-bottom: solid 1px lightgray;
        background-color: lightgray;

    }
    main>div:nth-last-child{
        border-bottom: none;
    }
</style>
{% endblock %}

{% block main%}
<div class="container">
    <h2 class="text-center">二级大纲</h2>
    <br>
    {% for program in programs %}
    <main>
        <div style="display: flex;justify-content: space-between">
            第{{program.number}}天 {{program.sing}}
            <span>
                <a href="/program/detail/?program_id={{program.id}}&outline_id={{outline.id}}"><span class="glyphicon glyphicon-list"></span></a>
                <a href="/program/edit/?program_id={{program.id}}"><span class="glyphicon glyphicon-edit"></span></a>
                <a href="/program/delete/?program_id={{program.id}}"><span class="glyphicon glyphicon-remove-circle"></span></a>
            </span>
        </div>
        <div style="background-color: white">{{program.digest}}</div>
        {% for outline in outlines %}
        <div>{{outline.title}}</div>
        {% endfor %}
    </main>
    <br>
    {% endfor %}
    <br>
    <div class="text-center">
        <a href="/program/add/">
            <span class="glyphicon glyphicon-plus-sign"></span>
        </a>
    </div>
</div>
{% endblock %}